version: "3.9"

services:
  app:
    build: .
    container_name: fake-news-app
    ports:
      - "${PORT:-8000}:8000"
    restart: always
    env_file:
      - .env
  healthcheck:
    test: ["CMD-SHELL", "curl -s http://localhost:8000/health | grep '\"status\": \"ok\"' || exit 1"]
    interval: 30s
    timeout: 10s
    retries: 3



